spring.application.name=medigen-backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/medigen
spring.datasource.username=
spring.datasource.password= f77beea5-bfb3-4fc2-9d04-c3b9f6f3b000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect